Sopeonow_EMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('base.urls'))
]

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),

    path('employee/list', views.view_employees, name="list"),

    path('employee/add', views.add_employee, name="add"),
    path('employee/ajax/load-roles/', views.load_roles,
         name='ajax_load_roles'),  # AJAX
    path('employee/add/success', views.add_employee_success, name="addSuccess"),

    path('employee/update/<int:pk>/', views.update_employee, name='update'),

    path('employee/delete/<int:pk>/', views.delete_employee, name='delete'),

    path('employee/leave/<int:pk>/', views.leave_status, name='leave'),

    path('employee/view/<int:pk>/', views.employee_detail, name='view'),
]

base/models.py
from django.db import models
from django.core.validators import MaxValueValidator

# Create your models here.


class Department(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name


class Role(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name


class Employee(models.Model):
    name = models.CharField(max_length=100, null=True)
    dob = models.DateField(null=True)
    doj = models.DateField(null=True)
    department = models.ForeignKey(
        Department, on_delete=models.SET_NULL, blank=True, null=True)
    role = models.ForeignKey(
        Role, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=100, null=True)
    state = models.CharField(max_length=100, null=True)
    country = models.CharField(max_length=100, null=True)
    zipcode = models.PositiveIntegerField(
        null=True, validators=[MaxValueValidator(999999)])
    leaves = models.PositiveIntegerField(null=True, default=0)
    active = models.BooleanField(default=True)
    on_leave = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.name

base/forms.py
from django import forms
from base.models import Employee, Role
import datetime


class DateInput(forms.DateInput):
    input_type = 'date'


class AddEmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'}),
                   'dob': DateInput(attrs={'class': 'form-control'}),
                   'doj': DateInput(attrs={'class': 'form-control'}),
                   'department': forms.Select(attrs={'class': 'form-control', 'type': 'button'}),
                   'role': forms.Select(attrs={'class': 'form-control', 'type': 'button'}),
                   'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
                   'city': forms.TextInput(attrs={'class': 'form-control'}),
                   'state': forms.TextInput(attrs={'class': 'form-control'}),
                   'country': forms.TextInput(attrs={'class': 'form-control'}),
                   'zipcode': forms.NumberInput(attrs={'class': 'form-control'}),
                   'leaves': forms.NumberInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
                   'active': forms.CheckboxInput(),
                   'on_leave': forms.CheckboxInput(),
                   }

    def clean_dob(self):
        date = self.cleaned_data['dob']
        if date > datetime.date.today():  # 🖘 raise error if greater than
            raise forms.ValidationError(
                "Date of birth cannot be in the future!")
        return date

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['role'].queryset = Role.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['role'].queryset = Role.objects.filter(
                    department_id=department_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Role queryset
        elif self.instance.pk:
            self.fields['role'].queryset = self.instance.department.role_set.order_by(
                'name')

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AddEmployeeForm
from .models import *
from django.db.models import Q

# Create your views here.


def home(request):
    employees = Employee.objects.all().count()
    empOnLeave = Employee.objects.filter(on_leave=True).count()

    labels = ['Total Employees', 'Employees on leave']
    data = [employees, empOnLeave]

    context = {'employees': employees, 'empOnLeave': empOnLeave,
               'labels': labels, 'data': data}
    return render(request, 'base/home.html', context)


def view_employees(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    employees = Employee.objects.filter(
        Q(name__icontains=q) |
        Q(dob__icontains=q) |
        Q(doj__icontains=q) |
        Q(department__name__icontains=q) |
        Q(role__name__icontains=q) |
        Q(address__icontains=q) |
        Q(city__icontains=q) |
        Q(state__icontains=q) |
        Q(country__icontains=q) |
        Q(zipcode__icontains=q) |
        Q(leaves__icontains=q)
    )

    query = False
    if request.method == 'GET' and 'q' in request.GET:
        query = True

    employeesCount = employees.count()

    context = {'employees': employees,
               'employees_count': employeesCount, 'query': query}
    return render(request, 'base/view_employees.html', context)


def add_employee(request):
    form = AddEmployeeForm()
    if request.method == 'POST':
        form = AddEmployeeForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            if (obj.on_leave == True):
                obj.leaves += 1
            obj.save()
            return redirect('addSuccess')
    context = {'form': form, 'Title': 'Create'}
    return render(request, 'base/add_employee.html', context)


def add_employee_success(request):
    message = 'Employee Added successfully ✅'
    return render(request, 'base/success.html', {'message': message})


def update_employee(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    form = AddEmployeeForm(instance=employee)
    if request.method == 'POST':
        form = AddEmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            obj = form.save(commit=False)
            if (obj.on_leave):
                obj.leaves += 1
            obj.save()
            return redirect(f'/employee/view/{pk}')
    context = {'form': form, 'Title': 'Edit'}
    return render(request, 'base/add_employee.html', context)


# AJAX
def load_roles(request):
    department_id = request.GET.get('department_id')
    roles = Role.objects.filter(department_id=department_id).all()
    return render(request, 'base/role_dropdown_list_options.html', {'roles': roles})


def delete_employee(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    if request.method == 'POST':
        employee.delete()
        return redirect('list')
    message = f"Are you sure you want to delete {employee.name}?"
    return render(request, 'base/confirm.html', {'message': message})


def leave_status(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    status = ''
    if employee.on_leave:
        status = 'At work'
    else:
        status = 'On leave'

    if request.method == 'POST':
        if employee.on_leave:
            employee.on_leave = False
        else:
            employee.leaves += 1
            employee.on_leave = True

        employee.save()
        return redirect(f'/employee/view/{pk}')

    message = f"Are you sure you want to change {employee.name}'s status to {status}?"

    context = {'message': message}
    return render(request, 'base/confirm.html', context)


def employee_detail(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    formatted_dob = employee.dob.strftime("%x")
    formatted_doj = employee.doj.strftime("%x")
    context = {'emp': employee, 'dob': formatted_dob, 'doj': formatted_doj}
    return render(request, 'base/employee_details.html', context)

base/templates/base/add_employee.html
{% extends 'main.html' %}

{% block content %}

<div class="card container shadow bg-white rounded" id="add-employee-wrapper">
    <div class="card-body">
        {% for field in form %}
        {{ field.errors }}
        {% endfor %}
        <h3 class="card-title">{{Title}} Employee</h3>
        <form method="post" id="EmployeeForm" data-roles-url="{% url 'ajax_load_roles' %}" role="form" class="my-3">
            {% csrf_token %}
            <div class="row my-2">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="name">
                            Name: </label>
                        {{form.name}}
                    </div>
                </div>
            </div>
            <div class="row my-2">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="dob">
                            Date of Birth: </label>
                        {{ form.dob }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="doj">
                            Date of Joining: </label>
                        {{ form.doj }}
                    </div>
                </div>
            </div>
            <div class="row my-2">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="department">
                            Department: </label>
                        {{ form.department }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="role">
                            Designation: </label>
                        {{ form.role }}
                    </div>
                </div>
            </div>
            <div class="row my-2">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="address">
                            Address: </label>
                        {{ form.address }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group my-1">
                        <label for="country">
                            Country: </label>
                        {{ form.country }}
                    </div>
                    <div class="form-group my-1">
                        <label for="state">
                            State: </label>
                        {{ form.state }}
                    </div>
                </div>
            </div>
            <div class="row my-2">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="city">
                            City: </label>
                        {{ form.city }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="zipcode">
                            Zipcode: </label>
                        {{ form.zipcode }}
                    </div>
                </div>
            </div>
            <div class="row my-2">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="leaves">
                            No of leave days: </label>
                        {{ form.leaves }}
                    </div>
                </div>
                <div class="col-md-6" id="employee-add-check">
                    <div class="form-group employee-add-checkbox">
                        <label for="active">
                            Active: </label>
                        {{ form.active }}
                    </div>
                    <div class="form-group employee-add-checkbox">
                        <label for="on_leave">
                            On Leave: </label>
                        {{ form.on_leave }}
                    </div>
                </div>
            </div>
            <div id="employee-btn">
                <a href="{{request.META.HTTP_REFERER}}" class="btn btn-danger btn-cancel">Cancel</a>
                <input type="submit" value="Submit" class="btn btn-success btn-submit">
            </div>
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_department").change(function () {
        const url = $("#EmployeeForm").attr("data-roles-url");  // get the url of the `load_roles` view
        const departmentId = $(this).val();  // get the selected department ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /members/ajax/load-roles/ )
            data: {
                'department_id': departmentId       // GET parameters
            },
            success: function (data) {
                $("#id_role").html(data);
            }
        });

    });
</script>

{% endblock %}

base/templates/base/confirm.html
{% extends 'main.html' %}

{% block content %}

<div class="confirm-wrapper">
    <div class="card shadow bg-white rounded" id="confirm-card-wrapper">
        <form class="card-body" method="POST" action="">
            {% csrf_token %}
            <p>{{message}}</p>
            <div class="btns">
                <a class="btn btn-primary btn-cancel" href="{{request.META.HTTP_REFERER}}">Cancel</a>
                <input class="btn btn-danger btn-submit" type="submit" value="Confirm" />
            </div>
        </form>
    </div>
</div>

{% endblock content %}

base/templates/base/employee_details.html
{% extends 'main.html' %}

{% block content %}
{% load static %}
<!-- <992 <768-->

<div class="container employee-details-wrapper">
    <div class="card shadow bg-white rounded employee-details-card">
        <div>
            <img src="{% static '/images/profile.jpg' %}" alt="profile-image" class="rounded-circle">
        </div>
        <div class="employee-detail-content-wrapper">
            <div class="row" id="btn-edit">
                <div>
                    <a id="btn-edit-left" class="btn btn-outline-primary btn-cancel" href="{% url 'list' %}">Back to
                        Employee
                        List</a>
                </div>
                <div>
                    <a id="btn-edit-right" class="btn btn-outline-success btn-submit"
                        href="{% url 'update' emp.id %}">Edit
                        Employee
                        Details</a>
                </div>
            </div>
            <div id="employee-detail-content" class="row">
                <div class="employee-detail-name">
                    <h3>{{emp.name}}</h3>
                </div>
                <div id="employee-detail-content-left" class="col-md-6">
                    <div>
                        <h4>Basic Details</h4>
                        <p><b>Department:</b> {{emp.department}}</p>
                        <p><b>Designation:</b> {{emp.role}}</p>
                    </div>
                    <div>
                        <h4>Other Details</h4>
                        <p><b>No of Leaves Days:</b> {{emp.leaves}}</p>
                        <p><b>Leave/Working:</b>
                            {% if emp.on_leave %}
                            On leave
                            {% else %}
                            At work
                            {% endif %}
                        </p>
                        <p><b>Status:</b>
                            {% if emp.active %}
                            <span>Active</span>
                            {% else %}
                            <span>Inactive</span>
                            {% endif %}
                        </p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div>
                        <h4>Contact Details</h4>
                        <p><b>Address:</b> {{emp.address}}</p>
                        <div class="employee-details-address-content">
                            <div>
                                <p class="employee-details-address-content-left"><b>City:</b> {{emp.city}}</p>
                                <p class="employee-details-address-content-left"><b>Zipcode:</b> {{emp.zipcode}}</p>
                            </div>
                            <div>
                                <p><b>State:</b> {{emp.state}}</p>
                                <p><b>Country:</b> {{emp.country}}</p>
                            </div>
                        </div>
                    </div>
                    <div>
                        <div>
                            <h4>Personal Details</h4>
                            <p><b>Date of Birth:</b> {{dob}}</p>
                            <p><b>Date of Joining:</b> {{doj}}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div id="btn-bottom">
                {% if emp.on_leave %}
                <a class="btn btn-outline-primary btn-cancel" href="{% url 'leave' emp.id %}">Mark at work</a>
                {% else %}
                <a class="btn btn-outline-danger btn-cancel" href="{% url 'leave' emp.id %}">Mark on leave</a>
                {% endif %}
                <a class="btn btn-danger btn-submit" href="{% url 'delete' emp.id %}">Delete Employee</a>
            </div>
        </div>
    </div>

    {% endblock %}

base/templates/base/home.html
{% extends 'main.html' %}

{% block content %}

<div id="home-title-wrapper">
    <div class="card home-title shadow bg-white rounded">
        <div class="card-body">
            <p id="home-title-heading">Welcome to SOPEONOW EMS</p>
            <div id="home-title-content-wrapper">
                <div id="chart">
                    <canvas id="myChart1"></canvas>
                </div>
                <div id="home-title-card-wrapper">
                    <div class="home-title-card" id="home-title-card-left">
                        <div class="home-title-card-content">
                            <p class="home-title-card-content-p">Total employees</p>
                            <a class="btn btn-primary btn-submit" href="{% url 'list' %}">Employee
                                List</a>
                        </div>
                        <p class="home-title-card-number">{{employees}}</p>
                    </div>
                    <div class="home-title-card" id="home-title-card-right">
                        <div class="home-title-card-content">
                            <p class="home-title-card-content-p">Employees on leave</p>
                            <a class="btn btn-primary btn-submit" href="{% url 'add' %}">Create
                                Employee</a>
                        </div>
                        <p class="home-title-card-number">{{empOnLeave}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var ctx = document.getElementById('myChart1').getContext('2d');
    var myChart1 = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: {{ labels| safe}},
    datasets: [{
        label: 'Employee Chart',
        data: {{ data| safe}},
        backgroundColor: [
        'rgb(255, 80, 80, 1)',
        'rgb(0, 153, 255, 1)',
    ],
        borderColor: [
        'rgb(255, 80, 80, 1)',
        'rgb(0, 153, 255, 1)',
    ],
        borderWidth: 1
    }]
        },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    display: false
                },
            }],
        }
    }
    });
</script>

{% endblock %}

base/templates/base/leave_status.html
{% extends 'main.html' %}

{% block content %}

<div class="confirm-wrapper">
    <div class="card shadow bg-white rounded" id="confirm-card-wrapper">
        <form class="card-body" method="POST" action="">
            {% csrf_token %}
            <p>Are you sure you want to change leave status to <b>"{{status}}"</b>?</p>
            <div class="btns">
                <a class="btn btn-primary" href="{{request.META.HTTP_REFERER}}">Cancel</a>
                <input class="btn btn-danger" type="submit" value="Confirm" />
            </div>
        </form>
    </div>
</div>

{% endblock content %}

base/templates/base/role_dropdown_list_options.html
<option value="">Select Role</option>
{% for role in roles %}
<option value="{{ role.pk }}">{{ role.name }}</option>
{% endfor %}

base/templates/base/success.html
{% extends 'main.html' %}

{% block content %}

<div class="confirm-wrapper">
    <div class="card shadow bg-white rounded" id="confirm-card-wrapper">
        <div class="card-body">
            <p>{{message}}</p>
            <div class="btns">
                <a class="btn btn-primary btn-submit" href="{% url 'list' %}">Go to Employee list</a>
                <a class="btn btn-primary btn-cancel" href="{% url 'add' %}">Add another employee</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

base/templates/base/view_employees.html
{% extends 'main.html' %}

{% block content %}

<div class="employee-list-wrapper">
    <div class="shadow bg-white rounded card employee-list-child-wrapper">
        <div class="card-body" id="employee-list-table-parent">
            <div id="employee-list-headers">
                <div>
                    <p id="employee-list-headers-employee">
                        {% if query %}
                        Search Results
                        {% else %}
                        Employee
                        {% endif %}
                        <span id="employee-list-headers-employee-count">{{employees_count}}</span>
                    </p>
                </div>
                <div>
                    <form action="{% url 'list' %}">
                        <input class="form-control" type="text" name="q" placeholder="Search employees..." />
                    </form>
                </div>
                <div>
                    {% if query %}
                    <a class="btn btn-primary btn-cancel" href="{% url 'list' %}">Go back</a>
                    {% endif %}
                    <a class="btn btn-submit" href="{% url 'add' %}">Create Employee</a>
                </div>
            </div>

            {% if employees %}
            <div id="employee-list-table">
                <div class="table-responsive">
                    <center>
                        <table class="table table-bordered table-sm align-middle text-center">
                            <thead>
                                <tr id="table-header">
                                    <th>Sr. No</th>
                                    <th>Name</th>
                                    <th>Department</th>
                                    <th>Designation</th>
                                    <th>Leave/Working</th>
                                    <th>View</th>
                                </tr>
                            </thead>

                            <tbody>
                                {% for emp in employees %}
                                <tr>
                                    <td>{{forloop.counter}}</td>
                                    <td>{{emp.name}}</td>
                                    <td>{{emp.department}}</td>
                                    <td>{{emp.role}}</td>
                                    <td>
                                        {% if emp.on_leave %}
                                        On leave
                                        {% else %}
                                        At work
                                        {% endif %}
                                    </td>
                                    <td><a class="btn btn-outline-primary btn-cancel"
                                            href="{% url 'view' emp.id %}">View</a>
                                    </td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </center>
                </div>
            </div>

            {% else %}
            <h3>No employees to show!</h3>

            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

base/templates/home.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Welcome home</h1>
</body>

</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sopeonow EMS</title>
    <link rel="icon" type="image/x-icon" href="/static/images/favicon.ico">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
</head>

<body>
    {% include 'navbar.html' %}
    <br>
    <div id="parent">
        <div class="container">
            {% block content %}


            {% endblock %}
        </div>
    </div>
</body>

</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-gradient">
    <div class="container container-fluid">
        <a class="navbar-brand" href="/">
            <img src="{% static '/images/logo.png' %}" alt="SOPEONOW" class="company-logo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>
            <ul class="navbar-nav">
                {% url 'home' as url %}
                <li class="nav-item">
                    <a class="nav-link active" id="{% if request.path == url %}current{% endif %}" aria-current="page"
                        href="{% url 'home' %}">Home</a>
                </li>
                {% url 'list' as url %}
                <li class="nav-item">
                    <a class="nav-link active" id="{% if request.path == url %}current{% endif %}" aria-current="page"
                        href="{% url 'list' %}">Employee
                        List</a>
                </li>
                {% url 'add' as url %}
                <li class="nav-item">
                    <a class="nav-link active" id="{% if request.path == url %}current{% endif %}" aria-current="page"
                        href="{% url 'add' %}">Create Employee</a>
                </li>
            </ul>
        </div>
    </div>
</nav>